Update apikey security handling
Per OAS documentation - apikey does not require a scheme property, hence this code fails:
```
 let authScheme = secDefinition.scheme.toLowerCase();
                                            ^
TypeError: Cannot read property 'toLowerCase' of undefined